<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?= _($title_form) ?></h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                <div class="form-group"><a class="_btn _secondary" href="<?= ($MyRequest->getRequest('callback') ? $Tokenizer->decode($MyRequest->getRequest('callback')) : $MyRequest->url(ADMIN_LISTA_CATEGORIAS_BLOG))?>" ><?= _('Atras') ?></a></div>
                <div class="form-group"><a class="_btn _primary save-form-top" href="#"><?= _('Guardar') ?></a></div>
            </div>
        </div>
    </div>
    <div class="w-xxxx-12">
         <div class="content_form">
            <?php echo $adminForm->openTag(); ?>
            <?php echo $adminForm->getRow('id'); ?>
            <?php echo $adminForm->getRow('callback'); ?>
            <?php if(getCoreConfig('blog/idioma/multi-idioma') == 1): ?>
              <?php echo $adminForm->getRow('lang'); ?>
             <?php endif; ?>
            <?php echo $adminForm->getRow('nombre'); ?>
            <?php echo $adminForm->getRow('visible'); ?>
            <?php echo $adminForm->getRow('permisos[]'); ?>
            <?php echo $adminForm->getRow('meta_keywords'); ?>
            <?php echo $adminForm->getRow('meta_titulo'); ?>
            <?php echo $adminForm->getRow('meta_descripcion'); ?>
            <?php echo $adminForm->getRow('guardar'); ?>
            <?php echo $adminForm->endTag(); ?>
       </div>
    </div>
</div>

<script >
$(document).ready(function(){
    $("#frmcategoria").validate();

    $('.save-form-top').click(function(e){
        e.preventDefault();
        $('#frmcategoria').trigger('submit');
    });
});
</script>
