<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?php echo _('Categorias'); ?></h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
            <form name="buscarGrid" action="" method="get" id="paginar">                
                <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
            </form>
      
                  <a href="<?php echo $MyRequest->url(ADMIN_FRM_CATEGORIAS_BLOG); ?>" class="_btn_new">Nuevo</a>
            
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>
<?php
$idiomas = array();
if(getCoreConfig('blog/idioma/multi-idioma') == 1)
{           
    $idiomas_disponibles = getCoreConfig('base/theme/langs');

    foreach($idiomas_disponibles as $idioma)
    {
        $idiomas[$idioma] = $idioma;
    }
}
?>
<script >
$(window).load(function(){
    var  langsData = <?= json_encode($idiomas)?>;
    langsData = Object.entries(langsData)
    .map(([id, nombre]) => `${id}:${nombre}`)
    .join(';');


    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'categoryBlog',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(ADMIN_FRM_CATEGORIAS_BLOG)?>',
        pathData : '<?=$MyRequest->url(ADMIN_LISTA_CATEGORIAS_BLOG)?>',
        error : "<?=_('No hay categorias registradas')?>",
        deleteFunction : "EliminarCategoriaBlog",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('Fecha registro')?>', name: 'fecha', width: 150,
                
                searchoptions: {
                    dataInit: function (element) {
                        $(element).datepicker({
                            id: 'orderDate_datePicker',
                            dateFormat:"yy-mm-dd",
                            maxDate: "+0D",
                            showOn: 'focus'
                        });
                    },
                    sopt: ["ge","le","eq"]
                }
            },
            { label: '<?=_('Nombre')?>', name: 'nombre', width: 250 },
            { label: '<?=_('Idioma')?>', name: 'lang', width: 150, stype: 'select',
                searchoptions: { value: langsData}
             },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 150, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        width:720
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(ADMIN_FRM_CATEGORIAS_BLOG)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton1 + boton2;
}

</script>
