<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?php echo _('Blog'); ?></h1>
        <div class="w-xxxx-12 cont_header_panel" style="">
            <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                    <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
                  <a href="<?php echo $MyRequest->url(ADMIN_FRM_ARTICULOS_BLOG); ?>" class="_btn_new">Nuevo</a>
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin ">
        <table id="jqGrid"></table>
        <div id="jqGridPager"></div>
        </div>
    </div>
</div>
<?php
$idiomas = array();
if(getCoreConfig('blog/idioma/multi-idioma') == 1)
{           
    $idiomas_disponibles = getCoreConfig('base/theme/langs');

    foreach($idiomas_disponibles as $idioma)
    {
        $idiomas[$idioma] = $idioma;
    }
}
?>
<script >
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    var  langsData = <?= json_encode($idiomas)?>;
    langsData = Object.entries(langsData)
    .map(([id, nombre]) => `${id}:${nombre}`)
    .join(';');


    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'blog',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(ADMIN_FRM_ARTICULOS_BLOG)?>',
        pathData : '<?=$MyRequest->url(ADMIN_LISTA_ARTICULOS_BLOG)?>',
        error : "<?=_('No hay articulos registrados')?>",
        deleteFunction : "EliminarArticuloBlog",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('Fecha registro')?>', name: 'fecha',hidden:isGridMobile,  width: 200,
                
                searchoptions: {
                    dataInit: function (element) {
                        $(element).datepicker({
                            id: 'orderDate_datePicker',
                            dateFormat:"yy-mm-dd",
                            maxDate: "+0D",
                            showOn: 'focus'
                        });
                    },
                    sopt: ["ge","le","eq"]
                }
            },
            { label: '<?=_('Titulo')?>', name: 'titulo', width: 250 },
            { label: '<?=_('Categoria')?>', name: 'categoria_nombre', width: 250 },
            { label: '<?=_('Autor')?>', name: 'nombre_user', hidden:isGridMobile, width: 250 },
            { label: '<?=_('Link')?>', name: 'friendly', hidden:isGridMobile, width: 250 },
            { label: '<?=_('Idioma')?>', name: 'lang', hidden:isGridMobile, width: 250, stype: 'select',
                searchoptions: { value: langsData}
             },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: isGridMobile,
        subGridRowExpanded: showChildGrid,
        width:1220
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(ADMIN_FRM_ARTICULOS_BLOG)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';
    if(rowObject.borrador == 1) {
        boton1 +=     '<a class="btn_adm_borrador"  href="<?=$MyRequest->link(ADMIN_FRM_ARTICULOS_BLOG)?>?id='+id+'&callback='+rowObject.callback+'&borrador=1"><span class="icon icon-borrar"> </span></a>';
    }
    return boton1 + boton2;
}

function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    
    if($(window).width() <= 767) {
      
        var fecha  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_fecha"]').text();
        var nombre  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_nombre_user"]').text();
        var url  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_friendly"]').text();
        var lang  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_lang"]').text();
      
        $('#' + parentRowID).append('<p>Fecha: '+fecha+'</p>');
        $('#' + parentRowID).append('<p>Nombre: '+nombre+'</p>');
        $('#' + parentRowID).append('<p>URL: '+url+'</p>');
        $('#' + parentRowID).append('<p>Idioma: '+lang+'</p>');
       
    }
}

</script>
